data: "../Data/female leftt arm mesh data.npz"
text_file: "../Models/Female Left Arm UV Mapped as Text.txt"
obj_file: "../Models/Female Left Arm UV Mapped.obj"
blend_file: "Models/Female Left Arm UV Mapping.blend"
base_mesh: "Models/Female Base Mesh.blend"