data: "../Data/female right arm mesh data.npz"
text_file: "../Models/Female Right Arm UV Mapped as Text.txt"
obj_file: "../Models/Female Right Arm UV Mapped.obj"
blend_file: "Models/Female Right Arm UV Mapping.blend"
base_mesh: "Models/Female Base Mesh.blend"